# Generated by Django 3.2.8 on 2021-10-26 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staff_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating mínimo é 1'), django.core.validators.MaxValueValidator(5, message='Rating máximo é 5')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='cover_url',
            field=models.URLField(null=True),
        ),
    ]
